### ISSUE TITLE
LMAO A bunch of this taken form my github

### ISSUE THREAD

**Issue by ItzBulkDev** [SavionLegendZzz/ServerCore#1]
LMAO and u calling me a kid. I see a bunch of these functions that are stolen from my github xD

**Comment by SavionLegendZzz** [comment]
wat functions....

**Comment by SavionLegendZzz** [comment]
this is not an issue if you are going to "say" that i toke functions from ur github please tweet to me

**Comment by ItzBulkDev** [comment]
there is a bunch of them stolen. You can clearly see it as github will automatically indent lines for you, but you copied and pasted it

**Comment by SavionLegendZzz** [comment]
yes i copyed and pasted from DroidEdit Free

**Comment by ItzBulkDev** [comment]
You can also tell you took a bunch my lines of code from SoundMIX if only bat and fizz and pop is used in the code why is there a launch?

**Comment by SavionLegendZzz** [comment]
theres is launch and etc cause i was testing which one too use and when did
u make a soundMIX?

**Comment by ItzBulkDev** [comment]
Savion, sorry for being mean lol. But can we be frands again? I'll buy you a free domain :)

**Comment by ItzBulkDev** [comment]
and I can help you with the errors.

**Comment by SavionLegendZzz** [comment]
it dosent have any erros atm

**Comment by ItzBulkDev** [comment]
it does, I have seen a bunch of errors lol no offense
